os: linux
dist: xenial
language: node_js
node_js:
  - "16.13.0"
branches:
  only:
    - main
    - develop
script:
  - npm run docs:build
deploy:
  provider: pages:git
  edge: true
  token: $GITHUB_TOKEN
  local_dir: docs/.vuepress/dist
  repo: GreenImp/rpg-dice-roller
  keep_history: false
  on:
    branch: main
    # all_branches: true

